# Generated by Django 4.2.1 on 2023-05-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
